name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        i18next-version: [8.4, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci --ignore-scripts
        npm install --ignore-scripts i18next@${{ matrix.i18next-version }}
        if [ $(echo "${{ matrix.i18next-version }} / 1" | bc) -lt 13 ]; then
          npm install --ignore-scripts @types/i18next@${{ matrix.i18next-version }}
        fi
        npm test
